dist: xenial

language: python
# show supported Python versions
python:
  - "3.7"
# Install dependencies
install:
 - pip install -r requirements.txt
services:
 - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4
# Run tests
before_script:
  - psql -c 'create database thephoenix;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
script: 
 - tox
 # Run coveralls
after_success:
 - coveralls
 