# Generated by Django 2.1.5 on 2019-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_rating',
            field=models.FloatField(default=0),
        ),
    ]
